import Head from "next/head";

import { useState, useEffect } from "react";
import Example from "../components/Example";
import HomeCard from "../components/HomeCard";
import Layout from "../components/Layout";

import styles from "../styles/Home.module.css";

export default function Home() {
  const [year, setYear] = useState("3rd");
  useEffect(() => {
    const localYear = localStorage.getItem("year");
    console.log(localYear);
    localYear && setYear(localYear);
  }, []);
  useEffect(() => {
    localStorage.setItem("year", year);
  }, [year]);

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>MME DEPARTMENT STUDENT CORNER</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/mmelogo2.png" />
        </Head>

        <main className={styles.main}>
          <h1>MME Student Corner</h1>
          <div className={styles.select}>
            <h3>Select your year</h3>
            <select
              onChange={(e) => setYear(e.target.value)}
              defaultValue={year}
            >
              <option value="2nd">2nd</option>
              <option value="3rd">3rd</option>
              <option value="4th">4th</option>
            </select>
          </div>
          <HomeCard year={year} />
        </main>
      </div>
    </Layout>
  );
}
